#if !canImport(ObjectiveC)
import XCTest

extension MarkdownFilterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MarkdownFilterTests = [
        ("testNodeCreation", testNodeCreation),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(MarkdownFilterTests.__allTests__MarkdownFilterTests),
    ]
}
#endif
